service_code: rocketmq
transport: stdio  # 支持 stdio 和  sse 和 StreamableHTTP
server_prot: 8888 # sse |  StreamableHTTP 模式需要设定端口
auth: none  # 支持 oauth 和 none
credential: env # 支持 env 和  token

#oauth:
#  client_id: your client id
#  client_secret: your client secret
#  authorize_url: 'https://github.com/login/oauth/authorize'
#  token_url: 'https://github.com/login/oauth/access_token'
#  scope: [user]